In [45]:
import pandas as pd
import datetime as dt
import pytz

from skyfield.api import N,S,E,W, wgs84, load

# location Port of Den Helder, Nieuwe diep:
lat = 52+(57/60)+(26.9/3600)
lon =  4+(46/60)+(37.5/3600)
height_m = 6
# fix1 @ 2019-12-31 08:41:44 UTC >>> 2019,12,31,08,41,44

# load raw data : observed Gyro & Sun
df = pd.read_csv('data/raw-gyro.csv')

# Skyfield setup
ts = load.timescale()
planets = load('de421.bsp')
earth, sun = planets['earth'], planets['sun']
Nieuwe_diep = earth + wgs84.latlon(lat * N, lon * E, elevation_m=height_m)

# Convert the 'time' column to datetime objects
# df['time'] = pd.to_datetime(df['time'])

# Add the date '2019-12-31' to each row
# df['date'] = pd.to_datetime('2019-12-31')

# Combine the date and time into a new datetime column 'datetime_UTC'
# df['datetime_UTC'] = pd.to_datetime(df['date'].dt.strftime('%Y-%m-%d') + ' ' + df['time'].dt.strftime('%H:%M:%S'))

df

,UTC,obs_sun_deg,obs_sun_min,obs_sun_sec,obs_gyro_deg_true
0,31-12-2019 08:41:44,343,41,24,155.063
1,31-12-2019 08:43:16,344,6,0,154.985
2,31-12-2019 08:44:12,344,16,44,155.055
3,31-12-2019 08:44:52,344,22,5,155.058
4,31-12-2019 08:46:01,344,35,30,155.076
5,31-12-2019 08:46:42,344,45,20,155.043
6,31-12-2019 08:47:21,344,60,38,154.940
7,31-12-2019 08:48:12,345,27,4,154.667
8,31-12-2019 08:48:58,345,41,55,154.588
9,31-12-2019 09:07:08,349,18,14,154.765
10,31-12-2019 09:07:24,349,23,44,154.764
11,31-12-2019 09:07:45,349,27,35,154.762
12,31-12-2019 09:08:03,349,33,42,154.783
13,31-12-2019 09:08:19,349,34,26,154.783
14,31-12-2019 09:08:34,349,38,59,154.779
15,31-12-2019 09:08:50,349,42,35,154.768
16,31-12-2019 09:09:13,349,51,28,154.733
17,31-12-2019 09:09:33,350,3,0,154.597
18,31-12-2019 09:09:57,350,16,46,154.509
19,31-12-2019 09:10:20,350,18,0,154.505

In [46]:
def dms_to_decimal(dms):
    degrees, minutes, seconds = map(float, dms.split())
    decimal_degrees = degrees + minutes / 60 + seconds / 3600
    return decimal_degrees

# Voorbeeld DataFrame
data = {
    'UTC': ['31-12-2019 08:41:44', '31-12-2019 08:43:16', '31-12-2019 08:44:12', '31-12-2019 08:44:52'],
    'obs_sun_deg': [343, 344, 344, 344],
    'obs_sun_min': [41, 6, 16, 22],
    'obs_sun_sec': [24, 0, 44, 5],
    'obs_gyro_deg_true': [155.063, 154.985, 155.055, 155.058]
}
df3 = pd.DataFrame(data)

# Combineer DMS-waarden in een enkele kolom
df3['obs_sun_dms'] = df3['obs_sun_deg'].astype(str) + ' ' + df3['obs_sun_min'].astype(str) + ' ' + df3['obs_sun_sec'].astype(str)


# Zet DMS om naar decimale graden en sla het op in een nieuwe kolom
df3['obs_sun_decimal'] = df3['obs_sun_dms'].apply(dms_to_decimal)

df3['obs_sun_dms'] = df3['obs_sun_deg'].astype(str) + '°' + df3['obs_sun_min'].astype(str) + '′' + df3['obs_sun_sec'].astype(str) + '″'

df3

def dms_to_string(degrees, minutes, seconds):
    """
    Convert degrees, minutes, seconds to a string in DMS format.
    
    Args:
        degrees (pd.Series): Degrees part of DMS.
        minutes (pd.Series): Minutes part of DMS.
        seconds (pd.Series): Seconds part of DMS.
        
    Returns:
        pd.Series: Series of strings in DMS format.
    """
    dms_string = degrees.astype(str) + u'\u00B0' + minutes.astype(str).str.zfill(2) + '′' + seconds.astype(str).str.zfill(2) + '″'
    return dms_string

df = pd.DataFrame(data)

# Converteer graden, minuten, seconden naar DMS-notatie en sla het op in een nieuwe kolom
df['obs_sun_dms'] = dms_to_string(df['obs_sun_deg'], df['obs_sun_min'], df['obs_sun_sec'])

def decimal_to_dms(decimal_degrees):
    """
    Convert decimal degrees to DMS format.
    
    Args:
        decimal_degrees (float or pd.Series): Decimal degrees to convert.
        
    Returns:
        str or pd.Series: DMS formatted string.
    """
    
    def convert_to_dms(dd):
        is_positive = dd >= 0
        dd = abs(dd)
        degrees = int(dd)
        minutes = int((dd - degrees) * 60)
        seconds = (dd - degrees - minutes / 60) * 3600
        sign = '' if is_positive else '-'
        dms_string = u'{0}{1}°{2:02}′{3:05.2f}″'.format(sign, degrees, minutes, seconds)
        return dms_string

    if isinstance(decimal_degrees, pd.Series):
        return decimal_degrees.apply(convert_to_dms)
    else:
        return convert_to_dms(decimal_degrees)

# Converteer decimale graden naar DMS-notatie en sla het op in een nieuwe kolom
df['obs_gyro_dms'] = decimal_to_dms(df['obs_gyro_deg_true'])

df.drop(['obs_sun_deg', 'obs_sun_min', 'obs_sun_sec'], axis=1, inplace=True)
# Toon het resultaat
print(df)

                   UTC  obs_gyro_deg_true obs_sun_dms   obs_gyro_dms
0  31-12-2019 08:41:44            155.063  343°41′24″  155°03′46.80″
1  31-12-2019 08:43:16            154.985  344°06′00″  154°59′06.00″
2  31-12-2019 08:44:12            155.055  344°16′44″  155°03′18.00″
3  31-12-2019 08:44:52            155.058  344°22′05″  155°03′28.80″

In [47]:
import pandas as pd

def dms_to_string(degrees, minutes, seconds):
    """
    Convert degrees, minutes, seconds to a string in DMS format.
    
    Args:
        degrees (pd.Series): Degrees part of DMS.
        minutes (pd.Series): Minutes part of DMS.
        seconds (pd.Series): Seconds part of DMS.
        
    Returns:
        pd.Series: Series of strings in DMS format.
    """
    dms_string = degrees.astype(str) + u'\u00B0' + minutes.astype(str).str.zfill(2) + '′' + seconds.astype(str).str.zfill(2) + '″'
    return dms_string

df = pd.DataFrame(data)

# Converteer graden, minuten, seconden naar DMS-notatie en sla het op in een nieuwe kolom
df['obs_sun_dms'] = dms_to_string(df['obs_sun_deg'], df['obs_sun_min'], df['obs_sun_sec'])

# Toon het resultaat
print(df)


def decimal_to_dms(decimal_degrees):
    """
    Convert decimal degrees to DMS format.
    
    Args:
        decimal_degrees (float or pd.Series): Decimal degrees to convert.
        
    Returns:
        str or pd.Series: DMS formatted string.
    """
    
    def convert_to_dms(dd):
        is_positive = dd >= 0
        dd = abs(dd)
        degrees = int(dd)
        minutes = int((dd - degrees) * 60)
        seconds = (dd - degrees - minutes / 60) * 3600
        sign = '' if is_positive else '-'
        dms_string = u'{0}{1}°{2:02}′{3:05.2f}″'.format(sign, degrees, minutes, seconds)
        return dms_string

    if isinstance(decimal_degrees, pd.Series):
        return decimal_degrees.apply(convert_to_dms)
    else:
        return convert_to_dms(decimal_degrees)

# Converteer decimale graden naar DMS-notatie en sla het op in een nieuwe kolom
df['obs_gyro_dms'] = decimal_to_dms(df['obs_gyro_deg_true'])

# Toon het resultaat

                   UTC  obs_sun_deg  obs_sun_min  obs_sun_sec  \
0  31-12-2019 08:41:44          343           41           24
1  31-12-2019 08:43:16          344            6            0
2  31-12-2019 08:44:12          344           16           44
3  31-12-2019 08:44:52          344           22            5

   obs_gyro_deg_true obs_sun_dms
0            155.063  343°41′24″
1            154.985  344°06′00″
2            155.055  344°16′44″
3            155.058  344°22′05″

In [48]:
# Functie om UTC naar CET of CEST te converteren op basis van de datum
def utc_to_cet_or_cest(utc_dt):
    # Definieer de tijdzones
    utc_zone = pytz.utc
    cet_zone = pytz.timezone('Europe/Amsterdam')
    
    # Zet de datetime naar een aware datetime in UTC
    utc_dt = utc_zone.localize(utc_dt)
    
    # Converteer naar CET of CEST
    cet_or_cest_dt = utc_dt.astimezone(cet_zone)
    
    return cet_or_cest_dt

# Functie om de juiste kolomnaam te bepalen en de waarde toe te voegen
def add_localtime_column(row):
    cet_or_cest_dt = utc_to_cet_or_cest(row['datetime_UTC'])
    if cet_or_cest_dt.tzname() == 'CEST':
        row['localtime_CEST'] = cet_or_cest_dt
    else:
        row['localtime_CET'] = cet_or_cest_dt
    return row

In [49]:
df2 = pd.read_csv(io.StringIO(data), sep=' \s+', engine='python')
df2['datetime_UTC'] = pd.to_datetime(df2['datetime_UTC'])

df2['cdt'] = df2['datetime_UTC'].dt.strftime('%Y,%m,%d,%H,%M,%S')
# note I changed the formatting to remove spaces for later parsing

def datetime_to_tuple(dt):
    return (dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second)

df2['time_tuple'] = df2['datetime_UTC'].apply(datetime_to_tuple)

df2.head()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Luke\AppData\Local\Temp\ipykernel_19960\3515590162.py:1: SyntaxWarning: invalid escape sequence '\s'
  df2 = pd.read_csv(io.StringIO(data), sep=' \s+', engine='python')

NameError: name 'io' is not defined

In [ ]:
import pandas as pd

def dms_to_decimal(degrees, minutes, seconds):
    """
    Convert degrees, minutes, seconds to decimal degrees.
    
    Args:
        degrees (pd.Series or int or float): Degrees part of DMS.
        minutes (pd.Series or int or float): Minutes part of DMS.
        seconds (pd.Series or int or float): Seconds part of DMS.
        
    Returns:
        pd.Series or float: Decimal degrees.
    """
    decimal_degrees = degrees + minutes / 60 + seconds / 3600
    return decimal_degrees

def decimal_to_dms(decimal_degrees):
    """
    Convert decimal degrees to DMS format.
    
    Args:
        decimal_degrees (float or pd.Series): Decimal degrees to convert.
        
    Returns:
        str or pd.Series: DMS formatted string.
    """
    def convert_to_dms(dd):
        is_positive = dd >= 0
        dd = abs(dd)
        degrees = int(dd)
        minutes = int((dd - degrees) * 60)
        seconds = (dd - degrees - minutes / 60) * 3600
        sign = '' if is_positive else '-'
        dms_string = u'{0}{1}°{2:02}′{3:05.2f}″'.format(sign, degrees, minutes, seconds)
        return dms_string

    if isinstance(decimal_degrees, pd.Series):
        return decimal_degrees.apply(convert_to_dms)
    else:
        return convert_to_dms(decimal_degrees)

# Voorbeeld DataFrame
data = {
    'UTC': ['31-12-2019 08:41:44', '31-12-2019 08:43:16', '31-12-2019 08:44:12', '31-12-2019 08:44:52'],
    'obs_sun_deg': [343, 344, 344, 344],
    'obs_sun_min': [41, 6, 16, 22],
    'obs_sun_sec': [24, 0, 44, 5],
    'obs_gyro_deg_true': [155.063, 154.985, 155.055, 155.058]
}
df = pd.DataFrame(data)

# Converteer graden, minuten, seconden naar decimale graden
df['obs_sun_decimal'] = dms_to_decimal(df['obs_sun_deg'], df['obs_sun_min'], df['obs_sun_sec'])

# Converteer decimale graden naar DMS-notatie en sla het op in een nieuwe kolom
df['obs_sun_dms'] = decimal_to_dms(df['obs_sun_decimal'])

# Verwijder de oorspronkelijke DMS-kolommen
df.drop(['obs_sun_deg', 'obs_sun_min', 'obs_sun_sec'], axis=1, inplace=True)

# Toon het resultaat
print(df)

                   UTC  obs_gyro_deg_true  obs_sun_decimal    obs_sun_dms
0  31-12-2019 08:41:44            155.063       343.690000  343°41′24.00″
1  31-12-2019 08:43:16            154.985       344.100000  344°06′00.00″
2  31-12-2019 08:44:12            155.055       344.278889  344°16′44.00″
3  31-12-2019 08:44:52            155.058       344.368056  344°22′05.00″

In [44]:
import pandas as pd
import datetime as dt
from skyfield.api import N,S,E,W, wgs84, load
import pytz
from timezonefinder import TimezoneFinder

# location Port of Den Helder, Nieuwe diep:
lat = 52 + (57 / 60) + (26.9 / 3600)
lon = 4 + (46 / 60) + (37.5 / 3600)
height_m = 6

# Skyfield setup
ts = load.timescale()
planets = load('de421.bsp') # plantary ephemeris dictionary
earth, sun = planets['earth'], planets['sun']
locale = earth + wgs84.latlon(lat * N, lon * E, elevation_m=height_m)

# input data
df = pd.read_csv('data/raw-gyro.csv')
#print(df.head())


# functions ----------------------------------------------------------------------
def dms_to_decimal(degrees, minutes, seconds):
    """
    Convert degrees, minutes, seconds to decimal degrees.
    
    Args:
        degrees (pd.Series or int or float): Degrees part of DMS.
        minutes (pd.Series or int or float): Minutes part of DMS.
        seconds (pd.Series or int or float): Seconds part of DMS.
        
    Returns:
        pd.Series or float: Decimal degrees.
    """
    decimal_degrees = degrees + minutes / 60 + seconds / 3600
    return decimal_degrees

def decimal_to_dms(decimal_degrees):
    """
    Convert decimal degrees to DMS format.
    
    Args:
        decimal_degrees (float or pd.Series): Decimal degrees to convert.
        
    Returns:
        str or pd.Series: DMS formatted string.
    """
    def convert_to_dms_string(dd):
        is_positive = dd >= 0
        dd = abs(dd)
        degrees = int(dd)
        minutes = int((dd - degrees) * 60)
        seconds = (dd - degrees - minutes / 60) * 3600
        sign = '' if is_positive else '-'
        dms_string = u'{0}{1}°{2:02}′{3:05.1f}″'.format(sign, degrees, minutes, seconds)
        return dms_string

    if isinstance(decimal_degrees, pd.Series):
        return decimal_degrees.apply(convert_to_dms)
    else:
        return convert_to_dms_string(decimal_degrees)

# Functie om UTC naar lokale tijd te converteren op basis van lat/lon en datum
def utc_to_localtime(utc_dt, lat=lat, lon=lon):
    # Definieer de tijdzone op basis van lat/lon
    tf = TimezoneFinder()
    timezone_str = tf.timezone_at(lng=lon, lat=lat)
    local_zone = pytz.timezone(timezone_str)
    
    # Zet de datetime naar een aware datetime in UTC
    utc_zone = pytz.utc
    utc_dt = utc_zone.localize(utc_dt)
    
    # Converteer naar lokale tijd
    local_dt = utc_dt.astimezone(local_zone)
    
    return local_dt

# Functie om de juiste kolomnaam te bepalen en de waarde toe te voegen
def add_localtime_column(row):
    utc_dt = row['UTC']
    local_dt = utc_to_localtime(utc_dt)
    
    if local_dt.tzname() == 'CEST':
        row['localtime_CEST'] = local_dt
    else:
        row['localtime_CET'] = local_dt
    
    return row

# Functie om de azimut te berekenen
def calculate_azimuth(utc_time):
    t = ts.utc(utc_time.year, utc_time.month, utc_time.day, utc_time.hour, utc_time.minute, utc_time.second)
    astro = locale.at(t).observe(sun)
    app = astro.apparent()
    _, az, _ = app.altaz()
    return az.degrees

# ---------------------------------------------------------------- 
# Convert the UTC column to datetime objects with UTC timezone
df['UTC'] = pd.to_datetime(df['UTC'], format='%d-%m-%Y %H:%M:%S') # [0]

df['obs_sun_decimal'] = dms_to_decimal(df['obs_sun_deg'], df['obs_sun_min'], df['obs_sun_sec']) #[1]
#df = df.drop(df.columns[[1, 2, 3]], axis=1)  # (remove raw D M S columns) df.columns is zero-based pd.Index 

df['obs_sun_dec'] = df.apply(lambda row: dms_to_decimal(row['obs_sun_deg'], row['obs_sun_min'], row['obs_sun_sec']), axis=1)

df = df.apply(add_localtime_column, axis=1) # [2] returns local timezone CET vor wintertime and CET for summertime


# Calculate azimuth for each row in the DataFrame and round to three decimal places
df['azimuth(Zn)'] = df['UTC'].apply(calculate_azimuth).round(3) 

df['Zn_dms'] = df['azimuth(Zn)'].apply(decimal_to_dms)
#df['gyro_obs_dms'] = df['obs_gyro_deg_true'].apply(decimal_to_dms)

# Convert UTC datetime objects to string with Zulu time format

KeyError: 'obs_sun_deg'

In [61]:


import pandas as pd
from skyfield.api import load, wgs84
from skyfield.api import N, E
import pytz
from timezonefinder import TimezoneFinder
from datetime import datetime

# Initialize the TimezoneFinder instance
tf = TimezoneFinder()

def get_timezone_by_location_and_date(lat, lon, date):
    """
    Get the timezone for a given location (latitude, longitude) and date.
    
    Args:
        lat (float): Latitude of the location.
        lon (float): Longitude of the location.
        date (datetime or str): Date for which the timezone is needed.
    
    Returns:
        str: The timezone name.
    """
    # Find the timezone name for the given latitude and longitude
    timezone_str = tf.timezone_at(lat=lat, lng=lon)
    
    if timezone_str is None:
        raise ValueError("Could not determine the timezone for the provided location.")
    
    # Convert date to datetime if it's a string
    if isinstance(date, str):
        date = datetime.strptime(date, "%Y-%m-%d")
    
    # Get the correct timezone information for the date
    timezone = pytz.timezone(timezone_str)
    localized_date = timezone.localize(date)
    
    return timezone_str, localized_date

# Example DataFrame
data = {
    'UTC': ['31-12-2019 08:41:44', '31-12-2019 08:43:16', '31-12-2019 08:44:12', '31-12-2019 08:44:52'],
    'obs_sun_deg': [343, 344, 344, 344],
    'obs_sun_min': [41, 6, 16, 22],
    'obs_sun_sec': [24, 0, 44, 5],
    'obs_gyro_deg_true': [155.063, 154.985, 155.055, 155.058]
}
df = pd.DataFrame(data)

# Location Port of Den Helder, Nieuwe diep:
lat = 52 + (57 / 60) + (26.9 / 3600)
lon = 4 + (46 / 60) + (37.5 / 3600)
height_m = 6

# Skyfield setup
ts = load.timescale()
planets = load('de421.bsp')
earth, sun = planets['earth'], planets['sun']
Nieuwe_diep = earth + wgs84.latlon(lat * N, lon * E, elevation_m=height_m)

# Function to calculate azimuth
def calculate_azimuth(utc_time):
    t = ts.utc(utc_time.year, utc_time.month, utc_time.day, utc_time.hour, utc_time.minute, utc_time.second)
    astro = Nieuwe_diep.at(t).observe(sun)
    app = astro.apparent()
    _, az, _ = app.altaz()
    return az.degrees

# Convert the UTC column to datetime objects with UTC timezone
df['UTC'] = pd.to_datetime(df['UTC'], format='%d-%m-%Y %H:%M:%S').dt.tz_localize(pytz.UTC)

# Calculate azimuth for each row in the DataFrame and round to three decimal places
df['azimuth'] = df['UTC'].apply(calculate_azimuth).round(3)

# Append 'Z' to the UTC column to indicate UTC time
df['UTC'] = df['UTC'].dt.strftime('%d-%m-%Y %H:%M:%S%z')

# Drop the original DMS columns
df.drop(['obs_sun_deg', 'obs_sun_min', 'obs_sun_sec'], axis=1, inplace=True)

# Display the result
print(df)

# Get timezone by location and date
timezone_str, localized_date = get_timezone_by_location_and_date(lat, lon, '2019-12-31')
print(f"Timezone: {timezone_str}\t \t  location: ")#{location_info}")
print(f"Localized Date: {localized_date} DR: ")#({lat},{lon})"

                        UTC  obs_gyro_deg_true  azimuth
0  31-12-2019 08:41:44+0000            155.063  138.873
1  31-12-2019 08:43:16+0000            154.985  139.192
2  31-12-2019 08:44:12+0000            155.055  139.387
3  31-12-2019 08:44:52+0000            155.058  139.526
Timezone: Europe/Amsterdam	 	  location:
Localized Date: 2019-12-31 00:00:00+01:00 DR: